#define Destination_Path ''
#define Message_Length 105
#define End_Header       8

macro fixutil from EDIT
{

  ignore_case  = false;
  reg_exp_stat = false;
  insert_mode  =  true;

  set_global_int ('REG_EXP_STYLE', 0);

  // -----------------------------------------------
  // Проверка: "А то ли нам подсунули на обработку?" ;-)
  // -----------------------------------------------

  tof;

  if (not (search_fwd ('Generated by FIXUTIL',20))){
    run_macro("meerror^messagebox
      /T= Error
      /M= Loaded Text is NOT a FileEcho-Statistics generated by FixUtil
      /NW=1
      /B=1"
    );
    delay (10000);
    goto Exit;
  }

  working;
  push_undo;

  if (search_fwd('Press <──┘',0))
  { del_line;
    save_file;

    if (error_level != 0)
    {
      run_macro("meerror^messagebox
        /T= Error
        /M= Can't Save file
        /NW=1
        /B=1"
      );
      delay (10000);
      goto Exit;
    }
  }
  else
  {
      run_macro("meerror^messagebox
        /T= Error
        /M= Can't find 'Press <──┘' substring
        /NW=1
        /B=1"
      );
      delay (10000);
      goto Exit;
  }
Exit:
  pop_undo;
  undo;
  set_global_int('RESTORE', 0);
  run_macro("exit^exit /NP=1");

}
